// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFlJ9MJEhSH-Nn-Gmp-MM8PtZH8gLNmIU',
    appId: '1:335328504937:web:9b86f95ef94c407b46c6f8',
    messagingSenderId: '335328504937',
    projectId: 'to-do-list-app-b8475',
    authDomain: 'to-do-list-app-b8475.firebaseapp.com',
    databaseURL: 'https://to-do-list-app-b8475-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-app-b8475.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcbHjEnGav9_YWhJLiLZMvrY_yJ99IEmg',
    appId: '1:335328504937:android:3e1f5f1e381639fd46c6f8',
    messagingSenderId: '335328504937',
    projectId: 'to-do-list-app-b8475',
    databaseURL: 'https://to-do-list-app-b8475-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-app-b8475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcIWdyczfj4AkBfxKylWDkZn64OHR1gs',
    appId: '1:335328504937:ios:ab0dd5124e7c787a46c6f8',
    messagingSenderId: '335328504937',
    projectId: 'to-do-list-app-b8475',
    databaseURL: 'https://to-do-list-app-b8475-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-app-b8475.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbcIWdyczfj4AkBfxKylWDkZn64OHR1gs',
    appId: '1:335328504937:ios:ab0dd5124e7c787a46c6f8',
    messagingSenderId: '335328504937',
    projectId: 'to-do-list-app-b8475',
    databaseURL: 'https://to-do-list-app-b8475-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-app-b8475.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFlJ9MJEhSH-Nn-Gmp-MM8PtZH8gLNmIU',
    appId: '1:335328504937:web:9b86f95ef94c407b46c6f8',
    messagingSenderId: '335328504937',
    projectId: 'to-do-list-app-b8475',
    authDomain: 'to-do-list-app-b8475.firebaseapp.com',
    databaseURL: 'https://to-do-list-app-b8475-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-app-b8475.firebasestorage.app',
  );

}